// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler_models

var TableNames = struct {
	Posts            string
	SchemaMigrations string
	Users            string
}{
	Posts:            "posts",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
