// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler_models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Follower is an object representing the database table.
type Follower struct {
	UserID     int64     `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	FollowerID int64     `boil:"follower_id" json:"follower_id" toml:"follower_id" yaml:"follower_id"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *followerR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L followerL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FollowerColumns = struct {
	UserID     string
	FollowerID string
	CreatedAt  string
}{
	UserID:     "user_id",
	FollowerID: "follower_id",
	CreatedAt:  "created_at",
}

var FollowerTableColumns = struct {
	UserID     string
	FollowerID string
	CreatedAt  string
}{
	UserID:     "followers.user_id",
	FollowerID: "followers.follower_id",
	CreatedAt:  "followers.created_at",
}

// Generated where

var FollowerWhere = struct {
	UserID     whereHelperint64
	FollowerID whereHelperint64
	CreatedAt  whereHelpertime_Time
}{
	UserID:     whereHelperint64{field: "\"followers\".\"user_id\""},
	FollowerID: whereHelperint64{field: "\"followers\".\"follower_id\""},
	CreatedAt:  whereHelpertime_Time{field: "\"followers\".\"created_at\""},
}

// FollowerRels is where relationship names are stored.
var FollowerRels = struct {
	Follower string
	User     string
}{
	Follower: "Follower",
	User:     "User",
}

// followerR is where relationships are stored.
type followerR struct {
	Follower *User `boil:"Follower" json:"Follower" toml:"Follower" yaml:"Follower"`
	User     *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*followerR) NewStruct() *followerR {
	return &followerR{}
}

func (r *followerR) GetFollower() *User {
	if r == nil {
		return nil
	}
	return r.Follower
}

func (r *followerR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// followerL is where Load methods for each relationship are stored.
type followerL struct{}

var (
	followerAllColumns            = []string{"user_id", "follower_id", "created_at"}
	followerColumnsWithoutDefault = []string{"user_id", "follower_id"}
	followerColumnsWithDefault    = []string{"created_at"}
	followerPrimaryKeyColumns     = []string{"user_id", "follower_id"}
	followerGeneratedColumns      = []string{}
)

type (
	// FollowerSlice is an alias for a slice of pointers to Follower.
	// This should almost always be used instead of []Follower.
	FollowerSlice []*Follower
	// FollowerHook is the signature for custom Follower hook methods
	FollowerHook func(context.Context, boil.ContextExecutor, *Follower) error

	followerQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	followerType                 = reflect.TypeOf(&Follower{})
	followerMapping              = queries.MakeStructMapping(followerType)
	followerPrimaryKeyMapping, _ = queries.BindMapping(followerType, followerMapping, followerPrimaryKeyColumns)
	followerInsertCacheMut       sync.RWMutex
	followerInsertCache          = make(map[string]insertCache)
	followerUpdateCacheMut       sync.RWMutex
	followerUpdateCache          = make(map[string]updateCache)
	followerUpsertCacheMut       sync.RWMutex
	followerUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var followerAfterSelectMu sync.Mutex
var followerAfterSelectHooks []FollowerHook

var followerBeforeInsertMu sync.Mutex
var followerBeforeInsertHooks []FollowerHook
var followerAfterInsertMu sync.Mutex
var followerAfterInsertHooks []FollowerHook

var followerBeforeUpdateMu sync.Mutex
var followerBeforeUpdateHooks []FollowerHook
var followerAfterUpdateMu sync.Mutex
var followerAfterUpdateHooks []FollowerHook

var followerBeforeDeleteMu sync.Mutex
var followerBeforeDeleteHooks []FollowerHook
var followerAfterDeleteMu sync.Mutex
var followerAfterDeleteHooks []FollowerHook

var followerBeforeUpsertMu sync.Mutex
var followerBeforeUpsertHooks []FollowerHook
var followerAfterUpsertMu sync.Mutex
var followerAfterUpsertHooks []FollowerHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Follower) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Follower) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Follower) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Follower) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Follower) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Follower) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Follower) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Follower) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Follower) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range followerAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddFollowerHook registers your hook function for all future operations.
func AddFollowerHook(hookPoint boil.HookPoint, followerHook FollowerHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		followerAfterSelectMu.Lock()
		followerAfterSelectHooks = append(followerAfterSelectHooks, followerHook)
		followerAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		followerBeforeInsertMu.Lock()
		followerBeforeInsertHooks = append(followerBeforeInsertHooks, followerHook)
		followerBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		followerAfterInsertMu.Lock()
		followerAfterInsertHooks = append(followerAfterInsertHooks, followerHook)
		followerAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		followerBeforeUpdateMu.Lock()
		followerBeforeUpdateHooks = append(followerBeforeUpdateHooks, followerHook)
		followerBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		followerAfterUpdateMu.Lock()
		followerAfterUpdateHooks = append(followerAfterUpdateHooks, followerHook)
		followerAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		followerBeforeDeleteMu.Lock()
		followerBeforeDeleteHooks = append(followerBeforeDeleteHooks, followerHook)
		followerBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		followerAfterDeleteMu.Lock()
		followerAfterDeleteHooks = append(followerAfterDeleteHooks, followerHook)
		followerAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		followerBeforeUpsertMu.Lock()
		followerBeforeUpsertHooks = append(followerBeforeUpsertHooks, followerHook)
		followerBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		followerAfterUpsertMu.Lock()
		followerAfterUpsertHooks = append(followerAfterUpsertHooks, followerHook)
		followerAfterUpsertMu.Unlock()
	}
}

// OneG returns a single follower record from the query using the global executor.
func (q followerQuery) OneG(ctx context.Context) (*Follower, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single follower record from the query.
func (q followerQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Follower, error) {
	o := &Follower{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler_models: failed to execute a one query for followers")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all Follower records from the query using the global executor.
func (q followerQuery) AllG(ctx context.Context) (FollowerSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all Follower records from the query.
func (q followerQuery) All(ctx context.Context, exec boil.ContextExecutor) (FollowerSlice, error) {
	var o []*Follower

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler_models: failed to assign all query results to Follower slice")
	}

	if len(followerAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all Follower records in the query using the global executor
func (q followerQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all Follower records in the query.
func (q followerQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to count followers rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q followerQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q followerQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler_models: failed to check if followers exists")
	}

	return count > 0, nil
}

// Follower pointed to by the foreign key.
func (o *Follower) Follower(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FollowerID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// User pointed to by the foreign key.
func (o *Follower) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadFollower allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (followerL) LoadFollower(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFollower interface{}, mods queries.Applicator) error {
	var slice []*Follower
	var object *Follower

	if singular {
		var ok bool
		object, ok = maybeFollower.(*Follower)
		if !ok {
			object = new(Follower)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFollower)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFollower))
			}
		}
	} else {
		s, ok := maybeFollower.(*[]*Follower)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFollower)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFollower))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &followerR{}
		}
		args[object.FollowerID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &followerR{}
			}

			args[obj.FollowerID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Follower = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.FollowerFollowers = append(foreign.R.FollowerFollowers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FollowerID == foreign.ID {
				local.R.Follower = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.FollowerFollowers = append(foreign.R.FollowerFollowers, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (followerL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFollower interface{}, mods queries.Applicator) error {
	var slice []*Follower
	var object *Follower

	if singular {
		var ok bool
		object, ok = maybeFollower.(*Follower)
		if !ok {
			object = new(Follower)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFollower)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFollower))
			}
		}
	} else {
		s, ok := maybeFollower.(*[]*Follower)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFollower)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFollower))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &followerR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &followerR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Followers = append(foreign.R.Followers, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Followers = append(foreign.R.Followers, local)
				break
			}
		}
	}

	return nil
}

// SetFollowerG of the follower to the related item.
// Sets o.R.Follower to related.
// Adds o to related.R.FollowerFollowers.
// Uses the global database handle.
func (o *Follower) SetFollowerG(ctx context.Context, insert bool, related *User) error {
	return o.SetFollower(ctx, boil.GetContextDB(), insert, related)
}

// SetFollower of the follower to the related item.
// Sets o.R.Follower to related.
// Adds o to related.R.FollowerFollowers.
func (o *Follower) SetFollower(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"followers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"follower_id"}),
		strmangle.WhereClause("\"", "\"", 2, followerPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.FollowerID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FollowerID = related.ID
	if o.R == nil {
		o.R = &followerR{
			Follower: related,
		}
	} else {
		o.R.Follower = related
	}

	if related.R == nil {
		related.R = &userR{
			FollowerFollowers: FollowerSlice{o},
		}
	} else {
		related.R.FollowerFollowers = append(related.R.FollowerFollowers, o)
	}

	return nil
}

// SetUserG of the follower to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Followers.
// Uses the global database handle.
func (o *Follower) SetUserG(ctx context.Context, insert bool, related *User) error {
	return o.SetUser(ctx, boil.GetContextDB(), insert, related)
}

// SetUser of the follower to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Followers.
func (o *Follower) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"followers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, followerPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.UserID, o.FollowerID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &followerR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Followers: FollowerSlice{o},
		}
	} else {
		related.R.Followers = append(related.R.Followers, o)
	}

	return nil
}

// Followers retrieves all the records using an executor.
func Followers(mods ...qm.QueryMod) followerQuery {
	mods = append(mods, qm.From("\"followers\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"followers\".*"})
	}

	return followerQuery{q}
}

// FindFollowerG retrieves a single record by ID.
func FindFollowerG(ctx context.Context, userID int64, followerID int64, selectCols ...string) (*Follower, error) {
	return FindFollower(ctx, boil.GetContextDB(), userID, followerID, selectCols...)
}

// FindFollower retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFollower(ctx context.Context, exec boil.ContextExecutor, userID int64, followerID int64, selectCols ...string) (*Follower, error) {
	followerObj := &Follower{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"followers\" where \"user_id\"=$1 AND \"follower_id\"=$2", sel,
	)

	q := queries.Raw(query, userID, followerID)

	err := q.Bind(ctx, exec, followerObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler_models: unable to select from followers")
	}

	if err = followerObj.doAfterSelectHooks(ctx, exec); err != nil {
		return followerObj, err
	}

	return followerObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Follower) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Follower) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler_models: no followers provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(followerColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	followerInsertCacheMut.RLock()
	cache, cached := followerInsertCache[key]
	followerInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			followerAllColumns,
			followerColumnsWithDefault,
			followerColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(followerType, followerMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(followerType, followerMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"followers\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"followers\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "boiler_models: unable to insert into followers")
	}

	if !cached {
		followerInsertCacheMut.Lock()
		followerInsertCache[key] = cache
		followerInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single Follower record using the global executor.
// See Update for more documentation.
func (o *Follower) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the Follower.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Follower) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	followerUpdateCacheMut.RLock()
	cache, cached := followerUpdateCache[key]
	followerUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			followerAllColumns,
			followerPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler_models: unable to update followers, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"followers\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, followerPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(followerType, followerMapping, append(wl, followerPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to update followers row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to get rows affected by update for followers")
	}

	if !cached {
		followerUpdateCacheMut.Lock()
		followerUpdateCache[key] = cache
		followerUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q followerQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q followerQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to update all for followers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to retrieve rows affected for followers")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o FollowerSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FollowerSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler_models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), followerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"followers\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, followerPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to update all in follower slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to retrieve rows affected all in update all follower")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Follower) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Follower) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("boiler_models: no followers provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(followerColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	followerUpsertCacheMut.RLock()
	cache, cached := followerUpsertCache[key]
	followerUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			followerAllColumns,
			followerColumnsWithDefault,
			followerColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			followerAllColumns,
			followerPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("boiler_models: unable to upsert followers, could not build update column list")
		}

		ret := strmangle.SetComplement(followerAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(followerPrimaryKeyColumns) == 0 {
				return errors.New("boiler_models: unable to upsert followers, could not build conflict column list")
			}

			conflict = make([]string, len(followerPrimaryKeyColumns))
			copy(conflict, followerPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"followers\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(followerType, followerMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(followerType, followerMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "boiler_models: unable to upsert followers")
	}

	if !cached {
		followerUpsertCacheMut.Lock()
		followerUpsertCache[key] = cache
		followerUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single Follower record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Follower) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single Follower record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Follower) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler_models: no Follower provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), followerPrimaryKeyMapping)
	sql := "DELETE FROM \"followers\" WHERE \"user_id\"=$1 AND \"follower_id\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to delete from followers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to get rows affected by delete for followers")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q followerQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q followerQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler_models: no followerQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to delete all from followers")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to get rows affected by deleteall for followers")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o FollowerSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FollowerSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(followerBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), followerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"followers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, followerPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to delete all from follower slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to get rows affected by deleteall for followers")
	}

	if len(followerAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Follower) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("boiler_models: no Follower provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Follower) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFollower(ctx, exec, o.UserID, o.FollowerID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FollowerSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("boiler_models: empty FollowerSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FollowerSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FollowerSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), followerPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"followers\".* FROM \"followers\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, followerPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler_models: unable to reload all in FollowerSlice")
	}

	*o = slice

	return nil
}

// FollowerExistsG checks if the Follower row exists.
func FollowerExistsG(ctx context.Context, userID int64, followerID int64) (bool, error) {
	return FollowerExists(ctx, boil.GetContextDB(), userID, followerID)
}

// FollowerExists checks if the Follower row exists.
func FollowerExists(ctx context.Context, exec boil.ContextExecutor, userID int64, followerID int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"followers\" where \"user_id\"=$1 AND \"follower_id\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, userID, followerID)
	}
	row := exec.QueryRowContext(ctx, sql, userID, followerID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler_models: unable to check if followers exists")
	}

	return exists, nil
}

// Exists checks if the Follower row exists.
func (o *Follower) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FollowerExists(ctx, exec, o.UserID, o.FollowerID)
}
