// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler_models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Comments", testCommentsUpsert)

	t.Run("Followers", testFollowersUpsert)

	t.Run("Posts", testPostsUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Users", testUsersUpsert)
}
