// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler_models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testUserInvitations(t *testing.T) {
	t.Parallel()

	query := UserInvitations()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testUserInvitationsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserInvitationsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := UserInvitations().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserInvitationsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserInvitationSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testUserInvitationsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := UserInvitationExists(ctx, tx, o.Token)
	if err != nil {
		t.Errorf("Unable to check if UserInvitation exists: %s", err)
	}
	if !e {
		t.Errorf("Expected UserInvitationExists to return true, but got false.")
	}
}

func testUserInvitationsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	userInvitationFound, err := FindUserInvitation(ctx, tx, o.Token)
	if err != nil {
		t.Error(err)
	}

	if userInvitationFound == nil {
		t.Error("want a record, got nil")
	}
}

func testUserInvitationsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = UserInvitations().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testUserInvitationsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := UserInvitations().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testUserInvitationsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	userInvitationOne := &UserInvitation{}
	userInvitationTwo := &UserInvitation{}
	if err = randomize.Struct(seed, userInvitationOne, userInvitationDBTypes, false, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}
	if err = randomize.Struct(seed, userInvitationTwo, userInvitationDBTypes, false, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userInvitationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userInvitationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserInvitations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testUserInvitationsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	userInvitationOne := &UserInvitation{}
	userInvitationTwo := &UserInvitation{}
	if err = randomize.Struct(seed, userInvitationOne, userInvitationDBTypes, false, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}
	if err = randomize.Struct(seed, userInvitationTwo, userInvitationDBTypes, false, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = userInvitationOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = userInvitationTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func userInvitationBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func userInvitationAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func userInvitationAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func userInvitationBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func userInvitationAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func userInvitationBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func userInvitationAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func userInvitationBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func userInvitationAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *UserInvitation) error {
	*o = UserInvitation{}
	return nil
}

func testUserInvitationsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &UserInvitation{}
	o := &UserInvitation{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, userInvitationDBTypes, false); err != nil {
		t.Errorf("Unable to randomize UserInvitation object: %s", err)
	}

	AddUserInvitationHook(boil.BeforeInsertHook, userInvitationBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	userInvitationBeforeInsertHooks = []UserInvitationHook{}

	AddUserInvitationHook(boil.AfterInsertHook, userInvitationAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	userInvitationAfterInsertHooks = []UserInvitationHook{}

	AddUserInvitationHook(boil.AfterSelectHook, userInvitationAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	userInvitationAfterSelectHooks = []UserInvitationHook{}

	AddUserInvitationHook(boil.BeforeUpdateHook, userInvitationBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	userInvitationBeforeUpdateHooks = []UserInvitationHook{}

	AddUserInvitationHook(boil.AfterUpdateHook, userInvitationAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	userInvitationAfterUpdateHooks = []UserInvitationHook{}

	AddUserInvitationHook(boil.BeforeDeleteHook, userInvitationBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	userInvitationBeforeDeleteHooks = []UserInvitationHook{}

	AddUserInvitationHook(boil.AfterDeleteHook, userInvitationAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	userInvitationAfterDeleteHooks = []UserInvitationHook{}

	AddUserInvitationHook(boil.BeforeUpsertHook, userInvitationBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	userInvitationBeforeUpsertHooks = []UserInvitationHook{}

	AddUserInvitationHook(boil.AfterUpsertHook, userInvitationAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	userInvitationAfterUpsertHooks = []UserInvitationHook{}
}

func testUserInvitationsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserInvitationsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(userInvitationColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testUserInvitationsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserInvitationsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := UserInvitationSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testUserInvitationsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := UserInvitations().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	userInvitationDBTypes = map[string]string{`Token`: `text`, `UserID`: `bigint`, `Expiry`: `timestamp with time zone`}
	_                     = bytes.MinRead
)

func testUserInvitationsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(userInvitationPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(userInvitationAllColumns) == len(userInvitationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testUserInvitationsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(userInvitationAllColumns) == len(userInvitationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &UserInvitation{}
	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, userInvitationDBTypes, true, userInvitationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(userInvitationAllColumns, userInvitationPrimaryKeyColumns) {
		fields = userInvitationAllColumns
	} else {
		fields = strmangle.SetComplement(
			userInvitationAllColumns,
			userInvitationPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := UserInvitationSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testUserInvitationsUpsert(t *testing.T) {
	t.Parallel()

	if len(userInvitationAllColumns) == len(userInvitationPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := UserInvitation{}
	if err = randomize.Struct(seed, &o, userInvitationDBTypes, true); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserInvitation: %s", err)
	}

	count, err := UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, userInvitationDBTypes, false, userInvitationPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize UserInvitation struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert UserInvitation: %s", err)
	}

	count, err = UserInvitations().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
