// Code generated by SQLBoiler 4.18.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler_models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// UserInvitation is an object representing the database table.
type UserInvitation struct {
	Token     string    `boil:"token" json:"token" toml:"token" yaml:"token"`
	UserID    int64     `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *userInvitationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userInvitationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserInvitationColumns = struct {
	Token     string
	UserID    string
	CreatedAt string
}{
	Token:     "token",
	UserID:    "user_id",
	CreatedAt: "created_at",
}

var UserInvitationTableColumns = struct {
	Token     string
	UserID    string
	CreatedAt string
}{
	Token:     "user_invitations.token",
	UserID:    "user_invitations.user_id",
	CreatedAt: "user_invitations.created_at",
}

// Generated where

var UserInvitationWhere = struct {
	Token     whereHelperstring
	UserID    whereHelperint64
	CreatedAt whereHelpertime_Time
}{
	Token:     whereHelperstring{field: "\"user_invitations\".\"token\""},
	UserID:    whereHelperint64{field: "\"user_invitations\".\"user_id\""},
	CreatedAt: whereHelpertime_Time{field: "\"user_invitations\".\"created_at\""},
}

// UserInvitationRels is where relationship names are stored.
var UserInvitationRels = struct {
}{}

// userInvitationR is where relationships are stored.
type userInvitationR struct {
}

// NewStruct creates a new relationship struct
func (*userInvitationR) NewStruct() *userInvitationR {
	return &userInvitationR{}
}

// userInvitationL is where Load methods for each relationship are stored.
type userInvitationL struct{}

var (
	userInvitationAllColumns            = []string{"token", "user_id", "created_at"}
	userInvitationColumnsWithoutDefault = []string{"token", "user_id"}
	userInvitationColumnsWithDefault    = []string{"created_at"}
	userInvitationPrimaryKeyColumns     = []string{"token"}
	userInvitationGeneratedColumns      = []string{}
)

type (
	// UserInvitationSlice is an alias for a slice of pointers to UserInvitation.
	// This should almost always be used instead of []UserInvitation.
	UserInvitationSlice []*UserInvitation
	// UserInvitationHook is the signature for custom UserInvitation hook methods
	UserInvitationHook func(context.Context, boil.ContextExecutor, *UserInvitation) error

	userInvitationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userInvitationType                 = reflect.TypeOf(&UserInvitation{})
	userInvitationMapping              = queries.MakeStructMapping(userInvitationType)
	userInvitationPrimaryKeyMapping, _ = queries.BindMapping(userInvitationType, userInvitationMapping, userInvitationPrimaryKeyColumns)
	userInvitationInsertCacheMut       sync.RWMutex
	userInvitationInsertCache          = make(map[string]insertCache)
	userInvitationUpdateCacheMut       sync.RWMutex
	userInvitationUpdateCache          = make(map[string]updateCache)
	userInvitationUpsertCacheMut       sync.RWMutex
	userInvitationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userInvitationAfterSelectMu sync.Mutex
var userInvitationAfterSelectHooks []UserInvitationHook

var userInvitationBeforeInsertMu sync.Mutex
var userInvitationBeforeInsertHooks []UserInvitationHook
var userInvitationAfterInsertMu sync.Mutex
var userInvitationAfterInsertHooks []UserInvitationHook

var userInvitationBeforeUpdateMu sync.Mutex
var userInvitationBeforeUpdateHooks []UserInvitationHook
var userInvitationAfterUpdateMu sync.Mutex
var userInvitationAfterUpdateHooks []UserInvitationHook

var userInvitationBeforeDeleteMu sync.Mutex
var userInvitationBeforeDeleteHooks []UserInvitationHook
var userInvitationAfterDeleteMu sync.Mutex
var userInvitationAfterDeleteHooks []UserInvitationHook

var userInvitationBeforeUpsertMu sync.Mutex
var userInvitationBeforeUpsertHooks []UserInvitationHook
var userInvitationAfterUpsertMu sync.Mutex
var userInvitationAfterUpsertHooks []UserInvitationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserInvitation) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserInvitation) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserInvitation) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserInvitation) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserInvitation) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserInvitation) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserInvitation) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserInvitation) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserInvitation) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userInvitationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserInvitationHook registers your hook function for all future operations.
func AddUserInvitationHook(hookPoint boil.HookPoint, userInvitationHook UserInvitationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userInvitationAfterSelectMu.Lock()
		userInvitationAfterSelectHooks = append(userInvitationAfterSelectHooks, userInvitationHook)
		userInvitationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		userInvitationBeforeInsertMu.Lock()
		userInvitationBeforeInsertHooks = append(userInvitationBeforeInsertHooks, userInvitationHook)
		userInvitationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		userInvitationAfterInsertMu.Lock()
		userInvitationAfterInsertHooks = append(userInvitationAfterInsertHooks, userInvitationHook)
		userInvitationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		userInvitationBeforeUpdateMu.Lock()
		userInvitationBeforeUpdateHooks = append(userInvitationBeforeUpdateHooks, userInvitationHook)
		userInvitationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		userInvitationAfterUpdateMu.Lock()
		userInvitationAfterUpdateHooks = append(userInvitationAfterUpdateHooks, userInvitationHook)
		userInvitationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		userInvitationBeforeDeleteMu.Lock()
		userInvitationBeforeDeleteHooks = append(userInvitationBeforeDeleteHooks, userInvitationHook)
		userInvitationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		userInvitationAfterDeleteMu.Lock()
		userInvitationAfterDeleteHooks = append(userInvitationAfterDeleteHooks, userInvitationHook)
		userInvitationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		userInvitationBeforeUpsertMu.Lock()
		userInvitationBeforeUpsertHooks = append(userInvitationBeforeUpsertHooks, userInvitationHook)
		userInvitationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		userInvitationAfterUpsertMu.Lock()
		userInvitationAfterUpsertHooks = append(userInvitationAfterUpsertHooks, userInvitationHook)
		userInvitationAfterUpsertMu.Unlock()
	}
}

// OneG returns a single userInvitation record from the query using the global executor.
func (q userInvitationQuery) OneG(ctx context.Context) (*UserInvitation, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single userInvitation record from the query.
func (q userInvitationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserInvitation, error) {
	o := &UserInvitation{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler_models: failed to execute a one query for user_invitations")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all UserInvitation records from the query using the global executor.
func (q userInvitationQuery) AllG(ctx context.Context) (UserInvitationSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all UserInvitation records from the query.
func (q userInvitationQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserInvitationSlice, error) {
	var o []*UserInvitation

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "boiler_models: failed to assign all query results to UserInvitation slice")
	}

	if len(userInvitationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all UserInvitation records in the query using the global executor
func (q userInvitationQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all UserInvitation records in the query.
func (q userInvitationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to count user_invitations rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q userInvitationQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q userInvitationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "boiler_models: failed to check if user_invitations exists")
	}

	return count > 0, nil
}

// UserInvitations retrieves all the records using an executor.
func UserInvitations(mods ...qm.QueryMod) userInvitationQuery {
	mods = append(mods, qm.From("\"user_invitations\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_invitations\".*"})
	}

	return userInvitationQuery{q}
}

// FindUserInvitationG retrieves a single record by ID.
func FindUserInvitationG(ctx context.Context, token string, selectCols ...string) (*UserInvitation, error) {
	return FindUserInvitation(ctx, boil.GetContextDB(), token, selectCols...)
}

// FindUserInvitation retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserInvitation(ctx context.Context, exec boil.ContextExecutor, token string, selectCols ...string) (*UserInvitation, error) {
	userInvitationObj := &UserInvitation{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_invitations\" where \"token\"=$1", sel,
	)

	q := queries.Raw(query, token)

	err := q.Bind(ctx, exec, userInvitationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "boiler_models: unable to select from user_invitations")
	}

	if err = userInvitationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userInvitationObj, err
	}

	return userInvitationObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *UserInvitation) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserInvitation) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("boiler_models: no user_invitations provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userInvitationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userInvitationInsertCacheMut.RLock()
	cache, cached := userInvitationInsertCache[key]
	userInvitationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userInvitationAllColumns,
			userInvitationColumnsWithDefault,
			userInvitationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userInvitationType, userInvitationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userInvitationType, userInvitationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_invitations\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_invitations\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "boiler_models: unable to insert into user_invitations")
	}

	if !cached {
		userInvitationInsertCacheMut.Lock()
		userInvitationInsertCache[key] = cache
		userInvitationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single UserInvitation record using the global executor.
// See Update for more documentation.
func (o *UserInvitation) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the UserInvitation.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserInvitation) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userInvitationUpdateCacheMut.RLock()
	cache, cached := userInvitationUpdateCache[key]
	userInvitationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userInvitationAllColumns,
			userInvitationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("boiler_models: unable to update user_invitations, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_invitations\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userInvitationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userInvitationType, userInvitationMapping, append(wl, userInvitationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to update user_invitations row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to get rows affected by update for user_invitations")
	}

	if !cached {
		userInvitationUpdateCacheMut.Lock()
		userInvitationUpdateCache[key] = cache
		userInvitationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q userInvitationQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q userInvitationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to update all for user_invitations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to retrieve rows affected for user_invitations")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o UserInvitationSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserInvitationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("boiler_models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userInvitationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_invitations\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userInvitationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to update all in userInvitation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to retrieve rows affected all in update all userInvitation")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *UserInvitation) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserInvitation) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("boiler_models: no user_invitations provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userInvitationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userInvitationUpsertCacheMut.RLock()
	cache, cached := userInvitationUpsertCache[key]
	userInvitationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			userInvitationAllColumns,
			userInvitationColumnsWithDefault,
			userInvitationColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			userInvitationAllColumns,
			userInvitationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("boiler_models: unable to upsert user_invitations, could not build update column list")
		}

		ret := strmangle.SetComplement(userInvitationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(userInvitationPrimaryKeyColumns) == 0 {
				return errors.New("boiler_models: unable to upsert user_invitations, could not build conflict column list")
			}

			conflict = make([]string, len(userInvitationPrimaryKeyColumns))
			copy(conflict, userInvitationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"user_invitations\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(userInvitationType, userInvitationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userInvitationType, userInvitationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "boiler_models: unable to upsert user_invitations")
	}

	if !cached {
		userInvitationUpsertCacheMut.Lock()
		userInvitationUpsertCache[key] = cache
		userInvitationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single UserInvitation record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *UserInvitation) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single UserInvitation record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserInvitation) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("boiler_models: no UserInvitation provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userInvitationPrimaryKeyMapping)
	sql := "DELETE FROM \"user_invitations\" WHERE \"token\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to delete from user_invitations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to get rows affected by delete for user_invitations")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q userInvitationQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q userInvitationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("boiler_models: no userInvitationQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to delete all from user_invitations")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to get rows affected by deleteall for user_invitations")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o UserInvitationSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserInvitationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userInvitationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userInvitationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"user_invitations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userInvitationPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: unable to delete all from userInvitation slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "boiler_models: failed to get rows affected by deleteall for user_invitations")
	}

	if len(userInvitationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *UserInvitation) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("boiler_models: no UserInvitation provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserInvitation) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserInvitation(ctx, exec, o.Token)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserInvitationSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("boiler_models: empty UserInvitationSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserInvitationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserInvitationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userInvitationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_invitations\".* FROM \"user_invitations\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userInvitationPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "boiler_models: unable to reload all in UserInvitationSlice")
	}

	*o = slice

	return nil
}

// UserInvitationExistsG checks if the UserInvitation row exists.
func UserInvitationExistsG(ctx context.Context, token string) (bool, error) {
	return UserInvitationExists(ctx, boil.GetContextDB(), token)
}

// UserInvitationExists checks if the UserInvitation row exists.
func UserInvitationExists(ctx context.Context, exec boil.ContextExecutor, token string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_invitations\" where \"token\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, token)
	}
	row := exec.QueryRowContext(ctx, sql, token)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "boiler_models: unable to check if user_invitations exists")
	}

	return exists, nil
}

// Exists checks if the UserInvitation row exists.
func (o *UserInvitation) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserInvitationExists(ctx, exec, o.Token)
}
